package com.earningformula.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

// Material Design 3 colors
val md_theme_light_primary = Color(0xFF1976D2)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE3F2FD)
val md_theme_light_onPrimaryContainer = Color(0xFF0D47A1)
val md_theme_light_secondary = Color(0xFF388E3C)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE8F5E8)
val md_theme_light_onSecondaryContainer = Color(0xFF1B5E20)
val md_theme_light_tertiary = Color(0xFFFF9800)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFF3E0)
val md_theme_light_onTertiaryContainer = Color(0xFFE65100)
val md_theme_light_error = Color(0xFFD32F2F)
val md_theme_light_errorContainer = Color(0xFFFFEBEE)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFFB71C1C)
val md_theme_light_background = Color(0xFFFAFAFA)
val md_theme_light_onBackground = Color(0xFF212121)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF212121)
val md_theme_light_surfaceVariant = Color(0xFFF5F5F5)
val md_theme_light_onSurfaceVariant = Color(0xFF757575)
val md_theme_light_outline = Color(0xFFBDBDBD)
val md_theme_light_outlineVariant = Color(0xFFE0E0E0)
val md_theme_light_inverseSurface = Color(0xFF424242)
val md_theme_light_inverseOnSurface = Color(0xFFFFFFFF)
val md_theme_light_inversePrimary = Color(0xFF90CAF9)
